### ISSUE TITLE
dpi choice

### ISSUE THREAD

**Issue by mquantin** [sverweij/atom-graphviz-preview-plus#18] opened 2017-07-12 07:17 UTC
The use of option 
`graph [ dpi = 300 ]`
doesn't resize the graph area (it zoom)
either in the preview
and in the exported files

example: 
```dot
digraph {
graph [ dpi = 300 ];
        F -> B;
        A -> Q;
        A -> B;
	}
```

**Comment by sverweij** [comment] 2017-07-12 12:52
I've reproduced it - I'll investigate this weekend.

**Comment by sverweij** [comment] 2017-07-12 18:45
## Investigation - summary
- SVG rendition (and hence the preview) is consistent with GraphViz' output. 
- GraphViz' SVG output is _surprising_ (actually a known [bug](https://github.com/ellson/graphviz/issues/543) in GraphViz) 
- PNG rendition is _not_ consistent with GraphViz' PNG rendition. There is a potential solution, but if GraphViz' authors also consider the SVG treatment of the `dpi` attribute a defect I'd prefer their solution.

## comparison to GraphViz native output
Using GraphViz 2.40.1 (latest stable according to https://github.com/ellson/graphviz/releases):
  - with SVG output: `dot -Tsvg dpi.dot -odpi.svg` (see on the bottom) => this is the same as graphviz-preview-plus produces (both surprising b.t.w.)
- with PNG output: `dot -Tpng dpi.dot -odpi.png` (see second picture) => here graphviz is doing a better job

## GraphViz' SVG output
### graphviz produces a surprising svg
```xml
<svg width="558pt" height="483pt" viewBox="0.00 0.00 134.00 116.00">
    <!-- nodes and edges left out for brevity -->
</svg>
```
Translation: 
- the SVG is 558x483 points big ...
- ... but only show the top left 134x116 points of it.

### Is this a bug in GraphViz or a feature?
I think it is. 
According to the documentation (**emphasis** mine) ...
> dpi
> This specifies the expected number of pixels per inch on a display device. For bitmap output, this guarantees that text rendering will be done more accurately, both in size and in placement. **For SVG output, it is used to guarantee that the dimensions in the output correspond to the correct number of points or inches.**

GraphViz does adjust the width and height, but doesn't adjust the `viewBox` accordingly. 

As it turns out this is a known defect in GraphViz: https://github.com/ellson/graphviz/issues/543 (since 2011 :-/ )

## GraphViz' PNG output vs graphviz-preview-plus PNG output
- graphviz renders the PNG directly
- graphviz-preview-plus takes the graphviz SVG output and converts that to a PNG. 

As the SVG output is 'surprising', so is the PNG.

Possible solution: directly generate the PNG from graphviz (/ viz.js) instead of via the SVG.

### Attachments svg and png output from graphviz itself
#### SVG
![GraphViz SVG output for the offending input](https://user-images.githubusercontent.com/4822597/28131534-7c491b80-673a-11e7-84f2-e087f565b817.png)

#### PNG
![GraphViz PNG output for the offending input](https://user-images.githubusercontent.com/4822597/28132610-a25a7e06-673d-11e7-968c-34de917d5e2f.png)

**Comment by sverweij** [comment] 2017-07-12 20:54
- As you can see ☝️ I've started a workaround for the GraphViz svg problem. I've tested it locally and it achieves the goal (a bit crudely, admittedly).
- While writing the workaround a second came up (=> manually change the viewBox attribute in the svg output) which is probably more elegant and closer to expected behaviour (and fixes the png problem at the same time). I'll look into it later (need sleep now).

**Comment by mquantin** [comment] 2017-07-13 07:30
Great job! thanks for having investigated! 

## About the "minor" priority of the graphviz bug
As svg is scalable it makes sense to ignore (downplay) the dpi otion problems. (issue is only raised when you generate both svg and bitmap from the same `.dot` file)

## About your solutions
Good ideas!

### Viewbox
Changing the svg viewbox in electron when dpi is modified in dot file.
Good option! 

### Direct png
Generating directly the png file from the .dot file with viz.js.
- You would still generate preview with the svg in electron don't you? (or you'll switch rendering mode, managing pictures in DOM or something like that?)
- and make a download of the image: `image = Viz("digraph g { a -> b; }", { format: "png-image-element", scale: 2 });`? (What is the link between `scale` and `dpi` options?)

→ So the bug will persist on the rendering but the output file (png) will be ok.
This maybe not so nice solution.

### GraphViz
Bug fix in graphviz lib?
How and when will it impact the viz.js lib?

Great job BTW! usefull and nice!

**Comment by sverweij** [comment] 2017-07-13 07:54
@ generating the png directly with viz.js -> png-image-element would be the way to go there. For the cli variant it'd be simpler (`dot -Tpng input.dot -ooutput.png`). If I would go that route it would be _alongside_ the fix for the preview rendering (so the right click _save as png_ would not derive it from the svg in the preview anymore). But first I'll try to do the viewBox fix - stay tuned.
@ bug fix in GraphViz lib: my c knowledge is super rusty (last used ~20 years ago) so the only option would be to get a higher priority on the bug
@ impact on viz.js: viz.js is 'just' a project that compiles GraphViz to javascript, so if it's fixed in GraphViz a new version of viz.js would include the fix as well (mdaines is doing an excelent job on it lately)

**Closed** 2017-08-11 19:52 UTC

**Comment by sverweij** [comment] 2017-08-11 20:05
I made a workaround for the bug in graphviz' svg rendering & published to atom.io. It took some time because I had a tough time writing an automated test for it (and finally decided to take it up as technical debt and manually test it with each release).

Let me know if it works (or doesn't)
